=== AnnaRad14/web1/src/main/resources/device.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Price: boundary values -->
    <xs:simpleType name="PriceType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000000"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Power consumption: boundary values -->
    <xs:simpleType name="PowerConsumptionType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Component group: enumeration -->
    <xs:simpleType name="GroupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Input"/>
            <xs:enumeration value="Output"/>
            <xs:enumeration value="Multimedia"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Port: pattern -->
    <xs:simpleType name="PortType">
        <xs:restriction base="xs:string">
            <xs:pattern value="USB|COM|LPT"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Origin: pattern -->
    <xs:simpleType name="OriginType">
        <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Type information -->
    <xs:complexType name="TypeInfo">
        <xs:sequence>

            <xs:element name="Peripheral"
                        type="xs:boolean"/>

            <xs:element name="PowerConsumption"
                        type="PowerConsumptionType"/>

            <xs:element name="Cooler"
                        type="xs:boolean"/>

            <xs:element name="Group"
                        type="GroupType"/>

            <xs:element name="Port"
                        type="PortType"
                        minOccurs="1"
                        maxOccurs="5"/>

        </xs:sequence>
    </xs:complexType>


    <!-- One computer component -->
    <xs:complexType name="DeviceType">
        <xs:sequence>

            <xs:element name="Name"
                        type="xs:string"/>

            <xs:element name="Origin"
                        type="OriginType"/>

            <xs:element name="Price"
                        type="PriceType"/>

            <xs:element name="Type"
                        type="TypeInfo"/>

            <xs:element name="Critical"
                        type="xs:boolean"/>

        </xs:sequence>
    </xs:complexType>


    <!-- Root element -->
    <xs:element name="Device">
        <xs:complexType>

            <xs:sequence>

                <xs:element name="Component"
                            type="DeviceType"
                            minOccurs="1"
                            maxOccurs="unbounded"/>

            </xs:sequence>

        </xs:complexType>
    </xs:element>

</xs:schema>

=== AnnaRad14/web1/src/main/resources/device.xml
<?xml version="1.0" encoding="UTF-8"?>

<Device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="device.xsd">

    <Component>
        <Name>Logitech MX Master 3</Name>
        <Origin>Switzerland</Origin>
        <Price>3500</Price>

        <Type>
            <Peripheral>true</Peripheral>
            <PowerConsumption>5</PowerConsumption>
            <Cooler>false</Cooler>
            <Group>Input</Group>
            <Port>USB</Port>
        </Type>

        <Critical>false</Critical>
    </Component>

    <Component>
        <Name>Intel Core i7-14700K</Name>
        <Origin>USA</Origin>
        <Price>18500</Price>

        <Type>
            <Peripheral>false</Peripheral>
            <PowerConsumption>125</PowerConsumption>
            <Cooler>true</Cooler>
            <Group>Multimedia</Group>
            <Port>USB</Port>
        </Type>

        <Critical>true</Critical>
    </Component>

    <Component>
        <Name>Kingston Fury 32GB</Name>
        <Origin>USA</Origin>
        <Price>4200</Price>

        <Type>
            <Peripheral>false</Peripheral>
            <PowerConsumption>15</PowerConsumption>
            <Cooler>false</Cooler>
            <Group>Multimedia</Group>
            <Port>USB</Port>
        </Type>

        <Critical>true</Critical>
    </Component>

    <Component>
        <Name>HP LaserJet Pro</Name>
        <Origin>USA</Origin>
        <Price>7200</Price>

        <Type>
            <Peripheral>true</Peripheral>
            <PowerConsumption>60</PowerConsumption>
            <Cooler>false</Cooler>
            <Group>Output</Group>
            <Port>USB</Port>
        </Type>

        <Critical>false</Critical>
    </Component>

</Device>
